-- Create orders table
CREATE TABLE IF NOT EXISTS orders (
    id BIGSERIAL PRIMARY KEY,
    order_id VARCHAR(64) NOT NULL UNIQUE,
    client_order_id VARCHAR(64),
    user_id VARCHAR(36) NOT NULL,
    account_id VARCHAR(36) NOT NULL,
    symbol VARCHAR(32) NOT NULL,
    side VARCHAR(4) NOT NULL CHECK (side IN ('BUY', 'SELL')),
    type VARCHAR(16) NOT NULL CHECK (type IN ('LIMIT', 'MARKET')),
    quantity NUMERIC(20, 8) NOT NULL CHECK (quantity > 0),
    price NUMERIC(20, 8) CHECK (price IS NULL OR price > 0),
    time_in_force VARCHAR(16) NOT NULL CHECK (time_in_force IN ('GTC', 'IOC', 'FOK')),
    status VARCHAR(32) NOT NULL CHECK (status IN ('PENDING', 'RISK_CHECKING', 'RISK_REJECTED', 'SUBMITTED', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED')),
    filled_quantity NUMERIC(20, 8) NOT NULL DEFAULT 0 CHECK (filled_quantity >= 0),
    avg_price NUMERIC(20, 8) CHECK (avg_price IS NULL OR avg_price >= 0),
    reject_reason VARCHAR(255),
    trace_id VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

-- Create indexes for common queries
CREATE INDEX idx_orders_user_created ON orders(user_id, created_at DESC);
CREATE INDEX idx_orders_symbol_status ON orders(symbol, status, created_at DESC);
CREATE INDEX idx_orders_client_order ON orders(client_order_id) WHERE client_order_id IS NOT NULL;
CREATE INDEX idx_orders_status ON orders(status, created_at DESC);

-- Create trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Create comment on table
COMMENT ON TABLE orders IS 'Trading orders table';
COMMENT ON COLUMN orders.order_id IS 'Unique order identifier generated by system';
COMMENT ON COLUMN orders.client_order_id IS 'Optional client-provided order ID for idempotency';
COMMENT ON COLUMN orders.filled_quantity IS 'Quantity that has been executed';
COMMENT ON COLUMN orders.avg_price IS 'Average execution price';
COMMENT ON COLUMN orders.version IS 'Optimistic locking version';
